[build]
  publish = "public"
  functions = "netlify/functions"

[functions]
  included_files = ["server/migrations/**"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/api/:splat"
  status = 200
